# Generated by Django 4.2 on 2025-04-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_company_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
    ]
