# Generated by Django 4.2 on 2025-04-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_usercompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='company',
            new_name='company_id',
        ),
    ]
