# Generated by Django 4.2 on 2025-04-02 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_company_department_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.department'),
        ),
    ]
