# Generated by Django 4.2 on 2025-04-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_usercompany_department_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercompany',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='usercompany',
            old_name='user_id',
            new_name='user',
        ),
    ]
