# Generated by Django 4.2 on 2025-04-03 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0005_rename_company_id_usercompany_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompany',
            name='id',
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
